name: Auto Update Projects

on:
  schedule:
    - cron: '0 0 * * *' # daily update
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch repos & build markdown
        run: |
          echo "## 🚀 Featured Projects" > PROJECTS.md
          echo "" >> PROJECTS.md
          curl -s https://api.github.com/users/ashwinisb70/repos?sort=updated | jq -r '.[] | "### [" + .name + "](" + .html_url + ")\n" + (.description // "No description") + "\n**Primary Language:** " + (.language // "N/A") + "\n\n"' >> PROJECTS.md

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add PROJECTS.md
          git commit -m "Auto generate projects"
          git push
